language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-adaptive' ]; then cd .. && eval "mv $currentfolder generator-angular-adaptive" && cd generator-angular-adaptive; fi

